name: FallenKingdom
main: fr.sl.main.MainClass
author: SimonLefebvre
version: 0.0
api-version: 1.13
commands:
  fkteam:
    description: on taffe dessus tkt
    usage: /<command> test
    permission: fallenkingdom.teammanagement
  fkteambase:
    description: assosie une a une base une team
  fkstart:
    description: fonction qui permet dans lancer le pl
  base:
    description: donne les coordones de la base du joueur